### ISSUE TITLE
docker-compose에서 .env 파일 읽도록 설정하는 방법

### ISSUE THREAD

**Issue by cotchan** [cotchan/front-back-cicd#3]
- The following syntax rules apply to the `.env` file

---

- 도커 컴포즈와 함께 사용 시 `env_file` 속성을 사용해서 환경변수 값을 읽어올 수 있습니다.

```yml
# docker-compose.yml

version: '3.8'
services:
  backend:
    container_name: app_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    env_file: ./.env
```

- `.env` 값 형태 예시

```
SPRING_PROFILES_ACTIVE=sandbox
SPRING_DATASOURCE_URL=jdbc:mysql
SPRING_DATASOURCE_USERNAME=
SPRING_DATASOURCE_PASSWORD=
```

---

- 참고
  - [Declare default environment variables in file](https://docs.docker.com/compose/env-file/) 
  - [How to pass configurations to Spring app running on Docker container](https://faun.pub/how-to-pass-configurations-to-spring-app-running-on-docker-container-f6e1f0ad66c4)
